server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

security.jwt.secret=a8b3c9d2e1f7g5h6j4k9m2n8p3q7r5s1t6v9ertsdkmndf2y8z0
