server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

security.jwt.secret=${JWT_SECRET:a8b3c9d2e1f7g5hdfddfSDGVdfdvf6poiuy456SKJHGj4k9m2nkhjfhdt8p3q7r5s1t6vwert5456789hjkliuygf9ertsdkmndf2y8z0}
