spring.application.name=log-analysis-service
server.port=8083

#Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5334/log_db
spring.datasource.username=root
spring.datasource.password=password

# Hibernate Configuration (Updates schema automatically based on your entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false