# إعدادات الخدمة الأساسية
spring.application.name=gamification-service
server.port=8084

# إعدادات الاتصال بقاعدة البيانات
spring.datasource.url=jdbc:postgresql://localhost:5335/gamification_db
spring.datasource.username=root
spring.datasource.password=password

# إعدادات Hibernate لإنشاء الجداول تلقائياً
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# إعدادات التسجيل في Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true