services:
  user-db:
    image: postgres:16
    container_name: user_microservice_db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_service_db
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
