spring.application.name=sprintify

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5332/user_service_db
spring.datasource.username=user_service
spring.datasource.password=123456

# Hibernate Configuration (Updates schema automatically based on your entities)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
security.jwt.secret=a8b3c9d2e1f7g5h6j4k9m2n8p3q7r5s1t6v9ertsdkmndf2y8z0
security.jwt.expiration-ms=86400000


