spring.application.name=identity-service
server.port=8081

#Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5332/user_service_db
spring.datasource.username=user_service
spring.datasource.password=123456

# Hibernate Configuration (Updates schema automatically based on your entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Configuration
security.jwt.secret=a8b3c9d2e1f7g5hdfddfSDGVdfdvf6poiuy456SKJHGj4k9m2nkhjfhdt8p3q7r5s1t6vwert5456789hjkliuygf9ertsdkmndf2y8z0
security.jwt.expiration-ms=86400000


